"boards.greenhouse.io/embed" = "greenhouse_embed"
"boards.greenhouse.io" = "greenhouse"
"jobs.lever.co" = "lever"
"bamboohr" = "bamboo"
"jobs.ashbyhq" = "ashby"
"apply.workable" = "workable"
"easyapply.co" = "easyapply"
"jobs.jobvite" = "jobvite"
".applytojob." = "applytojob"
"careers.smartrecruiters" = "smartrecruiter"
"recruitee.com" = "recruitee"