boards = [
    "greenhouse",
    "lever",
    "bamboo",
    "ashby",
    "workable",
    "easyapply",
    "jobvite",
    "applytojob",
    "smartrecruiter",
    "recruitee"
]
[url_chunks]
"boards.greenhouse.io/embed" = "greenhouse_embed"
"boards.greenhouse.io" = "greenhouse"
"?gh_jid=" = "greenhouse"
"jobs.lever.co" = "lever"
"bamboohr" = "bamboo"
"jobs.ashbyhq" = "ashby"
"apply.workable" = "workable"
"easyapply.co" = "easyapply"
"jobs.jobvite" = "jobvite"
".applytojob." = "applytojob"
"careers.smartrecruiters" = "smartrecruiter"
"recruitee" = "recruitee"

[url_templates]
"greenhouse" = "https://boards.greenhouse.io/$company"
"greenhouse_embed" = "https://boards.greenhouse.io/embed/job_board?for=$company"
"applytojob" = "https://$company.applytojob.com"
"ashby" = "https://jobs.ashbyhq.com/$company"
"bamboo" = "https://$company.bamboohr.com/careers"
"easyapply" = "https://$company.easyapply.co"
"jobvite" = "https://jobs.jobvite.com/$company/jobs"
"lever" = "https://jobs.lever.co/$company"
"recruitee" = "https://$company.recruitee.com"
"smartrecruiter" = "https://careers.smartrecruiters.com/$company"
"workable" = "https://apply.workable.com/$company"
