logs_dir = "logs"
scrapers_dir = "scrapers"
board_meta_path = "board_meta.toml"
careers_page_stubs_path = "careers_page_stubs.txt"
db_path = "jobs.db"
sql_dir = "sql"
templates_dir = "templates"
peruse_filters_path = "peruse_filters.toml"

[jobglob_daemon]
glob_interval = 3600
