"greenhouse" = "https://boards.greenhouse.io/$company"
"greenhouse_embed" = "https://boards.greenhouse.io/embed/job_board?for=$company"
"applytojob" = "https://$company.applytojob.com"
"ashby" = "https://jobs.ashbyhq.com/$company"
"bamboo" = "https://$company.bamboohr.com/careers"
"easyapply" = "https://$company.easyapply.co"
"jobvite" = "https://jobs.jobvite.com/$company/jobs"
"lever" = "https://jobs.lever.co/$company"
"recruitee" = "https://$company.recruitee.com"
"smartrecruiter" = "https://careers.smartrecruiters.com/$company"
"workable" = "https://apply.workable.com/$company"